name: Update README

on:
  push:
    branches:
    - master
    paths:
    - plugins.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update README
      run: rake readme
    - name: push
      run: |
        git config --global user.name 'Sketch Developer'
        git config --global user.email 'developer@sketch.com'
        git add README.md
        git commit -am 'Update README'
        git push
